const create = React.createElement

export class FAQ extends React.Component {
	render() {
		return create("div", { className: "faq" },
			create("div", { className: "section" },
				create("h3", {}, "What time should I arrive?"),
				create("p", {}, "The ceremony starts at 11:15am. Music, mingling, and drinks will begin a bit before 11am, so please arrive early!"),
			),
			create("div", { className: "section" },
				create("h3", {}, "Is there a dress code?"),
				create("p", {}, "We want you to be comfortable! That said, this is our wedding, so please no sweat pants or tattered tees. We recommend cocktail attire or 'smart casual' attire or anything you would wear on a date (that you're not trying to sabotage)."),
			),
			create("div", { className: "section" },
				create("h3", {}, "Are dogs allowed?"),
				create("p", {}, "We love dogs but they're not allowed in the club house, so it's not recommended. If you do decide to bring your doggo, make sure they don't cause a ruckus during the ceremony. There's a great dog park within Stern Grove just minutes away."),
			),
			create("div", { className: "section" },
				create("h3", {}, "Should I bring anything?"),
				create("p", {}, "Bring something warm - sweater, jacket, scarf or other layer! It probably won't rain this time of year (fingers crossed) but it's San Francisco in April near the ocean, so don't expect to sun bathe. The ceremony will be outdoors and the clubhouse has limited heating."),
			),
			create("div", { className: "section" },
				create("h3", {}, "Can I bring a gift in person?"),
				create("p", {}, "Of course! We set up the ", create("a", { href: "#gifts" }, "gifts page"), " because we thought it would be fun, and because it's notoriously difficult to buy a gift for any event, let alone a wedding."),
			),
			create("div", { className: "section" },
				create("h3", {}, "How do I get to the venue?"),
				create("p", {}, "Check out the ", create("a", { href: "#venue" }, "venue"), " page for instructions"),
			),
			create("div", { className: "section" },
				create("h3", {}, "Are you going to stream the wedding?"),
				create("p", {}, "Nope; sorry strangers on the internet. We'll take pictures instead!"),
			),
			create("div", { className: "section" },
				create("h3", {}, "May I steal something as a souvenir?"),
				create("p", {}, "Feel free to take a glass terrarium and/or wooden centerpiece. They're very pretty and we can't keep them all!"),
			),
			create("div", { className: "section" },
				create("h3", {}, "Why are you getting married?"),
				create("p", {}, "Dunno LOL. Just kidding, we adore each other and you should come to the wedding and cry with us."),
			),
			create("div", { className: "section" },
				create("h3", {}, "Why did you spend so much time making a custom website?"),
				create("p", {}, "A carpenter would make a hand-crafted table to commemorate the occasion. Meanwhile Luke is a nerd so instead you get a website. Here's the ", create("a", { href: "https://github.com/kixelated/couple.cool" }, "source code"), ".")
			),
			create("div", { className: "section" },
				create("h3", {}, "The website is ugly, maybe you should have consulted somebody with artistic ability?"),
				create("p", {}, "That wasn't a question; get out of our FAQ!")
			),
			create("div", { className: "section" },
				create("h3", {}, "I still have questions. Who do I contact?"),
				create("p", {}, "Feel free to email ", create("a", { href: "mailto: luke@couple.cool" }, "Luke"), " or ", create("a", { href: "mailto: rebe@couple.cool" }, "Rebecca"), "."),
			),
		)
	}
}
