const create = React.createElement

export class Home extends React.Component {
	render() {
		return create("div", { className: "home" },
			create("div", { className: "centerpiece" },
				create("div", { className: "names" },
					create("span", { className: "rebe" },
						create("img", { className: "bride", src: "images/kixelBride.png" }),
						"Rebe"
					),
					create("span", { className: "plus" }, "+"),
					create("span", { className: "luke" },
						"Luke",
						create("img", { className: "fancy", src: "images/kixelFancy.png" }),
					),
				),
				create("div", { className: "cool" }, "😎 the cool couple 😎"),
				create("div", { className: "date" }, "04.25.2020"),
			),
			create("div", { className: "intro section" },
				create("p", {}, "So we're getting married. That's cool I guess."),
				create("p", {}, "We're actually very excited! It's not every day that you get a chance to profess your love for another individual in front of friends/family. Plus it's a chance to eat, drink and be merry with said friends/family. So come, celebrate the occasion that is our marriage, and the start of the next phase of our life!"),
				create("p", { style: { textAlign: "center" } },
					create("a", { href: "#couple", className: "polaroid" },
						create("img", { src: "images/couple.jpg" }),
					),
				),
				create("p", { style: { marginTop: "2rem" } },
					"You can ",
					create("a", { href: "#couple" }, "read the origin story"),
					" of said cool couple, peruse ",
					create("a", { href: "#venue" }, "the venue"),
					", ",
					create("a", { href: "#schedule" }, "the schedule"),
					", and ",
					create("a", { href: "#faq" }, "everything else"),
					". ",
					"Finally, make sure you ",
					create("a", { href: "#rsvp" }, "RSVP"),
					" (even if you can't make it) and purhaps ",
					create("a", { href: "#gifts" }, "visit our registry"),
					" to shower us in gifts. So many posibilities!",
				),
			),
		)
	}
}
