const create = React.createElement

export class Venue extends React.Component {
	render() {
		return create("div", { className: "venue" },
			create("p", { className: "section" }, 
				create("h3", {}, "Stern Grove"),
				create("p", {}, "We're getting married in Stern Grove, a beautiful park in San Francisco. We've rented out the a small portion of this sweet park. Don't forget to bring your sweater!"),
				create("p", {}, "The ceremony, lunch, and part will be taking place at the Trocadero Clubhouse. It's a large yellow building with a parking lot and a cute lake, relatively close to the amphitheater."),
				create("div", { className: "polaroids" }, 
					create("div", { className: "polaroid" }, 
						create("img", { src: "images/stern2.jpg" }),
						create("p", {}, "Main Entrance"),
					),
					create("div", { className: "polaroid" }, 
						create("img", { src: "images/stern3.jpg" }),
						create("p", {}, "Trocadero Clubhouse"),
					),
				),
			),
			create("p", { className: "section" }, 
				create("h3", {}, "Directions"),
				create("p", {}, "The main park entrance is at the corner of 19th Ave and Sloat Blvd. The narrow road takes you straight to the clubhouse; you can't miss it!"),
				create("p", {}, create("strong", {}, "If you're driving:"), " There's a small parking lot in front of the clubhouse, but it's likely to be full. The park has a second entrance at Vale Ave and Sloat Blvd with a much larger parking lot, a short walk away from the clubhouse. If both are full, you'll have to scour for street parking so plan to arrive early."),
				create("p", {}, create("strong", {}, "If you're on foot:"), " The park has numerous trails and entrances. The clubhouse is located in the valley so don't panic when you start descending. Walking down the main entrance road is the easiest option."),
				create("p", {}, create("strong", {}, "If you're ride sharing:"), " You'll likely get dropped off at the main entrance; see above."),
				create("p", {}, create("strong", {}, "If you're taking the streetcar:"), " Take the M (Ocean View) or the K (Ingleside) and exit at the St. Francis Circle stop. Walk one block west to the main park entrance."),
				create("p", {}, create("strong", {}, "If you're taking the bus:"), " The 23 (Monterey) and the 28 (19th Avenue) stop right at the main etrance."),

				create("iframe", {
					frameBorder: 0,
					style: { 
						border: 0,
						width: "100%",
						maxWidth: "50rem",
						height: "30rem",
						margin: "0 auto",
						display: "block",
					},
					src: "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJIzHUu5d9j4ARtTe8PtcVMuk&key=AIzaSyBHbu8SRsWzGDQvAsOL9u3IDjWDydiv31w",
					allowfullscreen: true,
				}),
			),
			create("p", { className: "section" },
				create("h3", {}, "Schedule"),
				create("p", {}, "The ceremony starts at 11:15am and lunch is served immediately afterwards. The party will end by 3:30pm and we have a hard deadline to vacate the premises of all people and trash by 4:00pm. We may need help cleaning up!"),
				create("div", { className: "polaroids" },
					create("div", { className: "polaroid" },
						create("img", { src: "images/stern.jpg" }),
						create("p", {}, "THE SPOT"),
					),
				),
			),
		)
	}
}
